### ISSUE TITLE
Error loading module PolarClient

### ISSUE THREAD

**Issue by Triggered0** [FrantisekOmacka/Polar-client-source-code#1]
Error loading module PolarClient
org.mozilla.javascript.EcmaError: TypeError: Argument 0 is not Java class: [JavaPackage org.java_websocket.client.WebSocketClient]. (file:/C:/Users/DELL/AppData/Roaming/PrismLauncher/instances/Test/.minecraft/config/ChatTriggers/modules/WebSocket/index.js#16)
	at org.mozilla.javascript.ScriptRuntime.constructError(ScriptRuntime.java:4642)
	at org.mozilla.javascript.ScriptRuntime.constructError(ScriptRuntime.java:4622)
	at org.mozilla.javascript.ScriptRuntime.typeError(ScriptRuntime.java:4651)
	at org.mozilla.javascript.ScriptRuntime.typeError2(ScriptRuntime.java:4666)
	at org.mozilla.javascript.JavaAdapter.js_createAdapter(JavaAdapter.java:140)
	at org.mozilla.javascript.JavaAdapter.execIdCall(JavaAdapter.java:88)
	at org.mozilla.javascript.IdFunctionObject.call(IdFunctionObject.java:90)
	at org.mozilla.javascript.BaseFunction.construct(BaseFunction.java:442)
	at org.mozilla.javascript.ScriptRuntime.newObject(ScriptRuntime.java:2960)
	at WebSocket_index_js_1079._c_WebSocket_1(WebSocket/index.js:16)
	at WebSocket_index_js_1079.call(WebSocket/index.js)
	at org.mozilla.javascript.BaseFunction.construct(BaseFunction.java:436)
	at WebSocket_index_js_1079.construct(WebSocket/index.js)
	at org.mozilla.javascript.ScriptRuntime.newObject(ScriptRuntime.java:2960)
	at PolarClient_socket_Socket_js_1078._c_Socket_1(PolarClient/socket/Socket.js:24)
	at PolarClient_socket_Socket_js_1078.call(PolarClient/socket/Socket.js)
	at org.mozilla.javascript.BaseFunction.construct(BaseFunction.java:436)
	at PolarClient_socket_Socket_js_1078.construct(PolarClient/socket/Socket.js)
	at org.mozilla.javascript.ScriptRuntime.newObject(ScriptRuntime.java:2960)
	at PolarClient_socket_Socket_js_1078._c_script_0(PolarClient/socket/Socket.js:78)
	at PolarClient_socket_Socket_js_1078.call(PolarClient/socket/Socket.js)
	at PolarClient_socket_Socket_js_1078.exec(PolarClient/socket/Socket.js)
	at org.mozilla.javascript.commonjs.module.Require.executeModuleScript(Require.java:351)
	at org.mozilla.javascript.commonjs.module.Require.getExportedModuleInterface(Require.java:302)
	at org.mozilla.javascript.commonjs.module.Require.call(Require.java:232)
	at org.mozilla.javascript.optimizer.OptRuntime.callName(OptRuntime.java:74)
	at PolarClient_loader_js_1022._c_script_0(PolarClient/loader.js:1)
	at PolarClient_loader_js_1022.call(PolarClient/loader.js)
	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:342)
	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3951)
	at PolarClient_loader_js_1022.call(PolarClient/loader.js)
	at PolarClient_loader_js_1022.exec(PolarClient/loader.js)
	at org.mozilla.javascript.commonjs.module.Require.executeModuleScript(Require.java:351)
	at org.mozilla.javascript.commonjs.module.Require.getExportedModuleInterface(Require.java:302)
	at com.chattriggers.ctjs.engine.langs.js.JSLoader$CTRequire.loadCTModule(JSLoader.kt:329)

**Comment by Triggered0** [comment]
`Error loading module PolarClient
java.lang.NoClassDefFoundError: Lorg/slf4j/Logger;
	at java.lang.Class.getDeclaredFields0(Native Method)
	at java.lang.Class.privateGetDeclaredFields(Class.java:2583)
	at java.lang.Class.getDeclaredFields(Class.java:1916)
	at org.mozilla.javascript.JavaMembers.getAccessibleFields(JavaMembers.java:646)
	at org.mozilla.javascript.JavaMembers.reflect(JavaMembers.java:459)
	at org.mozilla.javascript.JavaMembers.<init>(JavaMembers.java:39)
	at org.mozilla.javascript.JavaMembers.lookupClass(JavaMembers.java:781)
	at org.mozilla.javascript.NativeJavaClass.initMembers(NativeJavaClass.java:49)
	at org.mozilla.javascript.NativeJavaObject.<init>(NativeJavaObject.java:47)
	at org.mozilla.javascript.NativeJavaClass.<init>(NativeJavaClass.java:43)
	at org.mozilla.javascript.JavaAdapter.js_createAdapter(JavaAdapter.java:184)
	at org.mozilla.javascript.JavaAdapter.execIdCall(JavaAdapter.java:88)
	at org.mozilla.javascript.IdFunctionObject.call(IdFunctionObject.java:90)
	at org.mozilla.javascript.BaseFunction.construct(BaseFunction.java:442)
	at org.mozilla.javascript.ScriptRuntime.newObject(ScriptRuntime.java:2960)
	at WebSocket_index_js_374._c_WebSocket_1(WebSocket/index.js:16)
	at WebSocket_index_js_374.call(WebSocket/index.js)
	at org.mozilla.javascript.BaseFunction.construct(BaseFunction.java:436)
	at WebSocket_index_js_374.construct(WebSocket/index.js)
	at org.mozilla.javascript.ScriptRuntime.newObject(ScriptRuntime.java:2960)
	at PolarClient_socket_Socket_js_373._c_Socket_1(PolarClient/socket/Socket.js:24)
	at PolarClient_socket_Socket_js_373.call(PolarClient/socket/Socket.js)
	at org.mozilla.javascript.BaseFunction.construct(BaseFunction.java:436)
	at PolarClient_socket_Socket_js_373.construct(PolarClient/socket/Socket.js)
	at org.mozilla.javascript.ScriptRuntime.newObject(ScriptRuntime.java:2960)
	at PolarClient_socket_Socket_js_373._c_script_0(PolarClient/socket/Socket.js:78)
	at PolarClient_socket_Socket_js_373.call(PolarClient/socket/Socket.js)
	at PolarClient_socket_Socket_js_373.exec(PolarClient/socket/Socket.js)
	at org.mozilla.javascript.commonjs.module.Require.executeModuleScript(Require.java:351)
	at org.mozilla.javascript.commonjs.module.Require.getExportedModuleInterface(Require.java:302)
	at org.mozilla.javascript.commonjs.module.Require.call(Require.java:232)
	at org.mozilla.javascript.optimizer.OptRuntime.callName(OptRuntime.java:74)
	at PolarClient_loader_js_317._c_script_0(PolarClient/loader.js:1)
	at PolarClient_loader_js_317.call(PolarClient/loader.js)
	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:342)
	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3951)
	at PolarClient_loader_js_317.call(PolarClient/loader.js)
	at PolarClient_loader_js_317.exec(PolarClient/loader.js)
	at org.mozilla.javascript.commonjs.module.Require.executeModuleScript(Require.java:351)
	at org.mozilla.javascript.commonjs.module.Require.getExportedModuleInterface(Require.java:302)
	at com.chattriggers.ctjs.engine.langs.js.JSLoader$CTRequire.loadCTModule(JSLoader.kt:329)
Caused by: java.lang.ClassNotFoundException: org.slf4j.Logger
	at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at java.lang.Class.getDeclaredFields0(Native Method)
	at java.lang.Class.privateGetDeclaredFields(Class.java:2583)
	at java.lang.Class.getDeclaredFields(Class.java:1916)
	at org.mozilla.javascript.JavaMembers.getAccessibleFields(JavaMembers.java:646)
	at org.mozilla.javascript.JavaMembers.reflect(JavaMembers.java:459)
	at org.mozilla.javascript.JavaMembers.<init>(JavaMembers.java:39)
	at org.mozilla.javascript.JavaMembers.lookupClass(JavaMembers.java:781)
	at org.mozilla.javascript.NativeJavaClass.initMembers(NativeJavaClass.java:49)
	at org.mozilla.javascript.NativeJavaObject.<init>(NativeJavaObject.java:47)
	at org.mozilla.javascript.NativeJavaClass.<init>(NativeJavaClass.java:43)
	at org.mozilla.javascript.JavaAdapter.js_createAdapter(JavaAdapter.java:184)
	at org.mozilla.javascript.JavaAdapter.execIdCall(JavaAdapter.java:88)
	at org.mozilla.javascript.IdFunctionObject.call(IdFunctionObject.java:90)
	at org.mozilla.javascript.BaseFunction.construct(BaseFunction.java:442)
	at org.mozilla.javascript.ScriptRuntime.newObject(ScriptRuntime.java:2960)
	at org.mozilla.javascript.gen.file__C__Users_DELL_AppData_Roaming_PrismLauncher_instances_Test__minecraft_config_ChatTriggers_modules_WebSocket_index_js_374._c_WebSocket_1(file:/C:/Users/DELL/AppData/Roaming/PrismLauncher/instances/Test/.minecraft/config/ChatTriggers/modules/WebSocket/index.js:16)
	at org.mozilla.javascript.gen.file__C__Users_DELL_AppData_Roaming_PrismLauncher_instances_Test__minecraft_config_ChatTriggers_modules_WebSocket_index_js_374.call(file:/C:/Users/DELL/AppData/Roaming/PrismLauncher/instances/Test/.minecraft/config/ChatTriggers/modules/WebSocket/index.js)
	at org.mozilla.javascript.BaseFunction.construct(BaseFunction.java:436)
	at org.mozilla.javascript.gen.file__C__Users_DELL_AppData_Roaming_PrismLauncher_instances_Test__minecraft_config_ChatTriggers_modules_WebSocket_index_js_374.construct(file:/C:/Users/DELL/AppData/Roaming/PrismLauncher/instances/Test/.minecraft/config/ChatTriggers/modules/WebSocket/index.js)
	at org.mozilla.javascript.ScriptRuntime.newObject(ScriptRuntime.java:2960)
	at org.mozilla.javascript.gen.file__C__Users_DELL_AppData_Roaming_PrismLauncher_instances_Test__minecraft_config_ChatTriggers_modules_PolarClient_socket_Socket_js_373._c_Socket_1(file:/C:/Users/DELL/AppData/Roaming/PrismLauncher/instances/Test/.minecraft/config/ChatTriggers/modules/PolarClient/socket/Socket.js:24)
	at org.mozilla.javascript.gen.file__C__Users_DELL_AppData_Roaming_PrismLauncher_instances_Test__minecraft_config_ChatTriggers_modules_PolarClient_socket_Socket_js_373.call(file:/C:/Users/DELL/AppData/Roaming/PrismLauncher/instances/Test/.minecraft/config/ChatTriggers/modules/PolarClient/socket/Socket.js)
	at org.mozilla.javascript.BaseFunction.construct(BaseFunction.java:436)
	at org.mozilla.javascript.gen.file__C__Users_DELL_AppData_Roaming_PrismLauncher_instances_Test__minecraft_config_ChatTriggers_modules_PolarClient_socket_Socket_js_373.construct(file:/C:/Users/DELL/AppData/Roaming/PrismLauncher/instances/Test/.minecraft/config/ChatTriggers/modules/PolarClient/socket/Socket.js)
	at org.mozilla.javascript.ScriptRuntime.newObject(ScriptRuntime.java:2960)
	at org.mozilla.javascript.gen.file__C__Users_DELL_AppData_Roaming_PrismLauncher_instances_Test__minecraft_config_ChatTriggers_modules_PolarClient_socket_Socket_js_373._c_script_0(file:/C:/Users/DELL/AppData/Roaming/PrismLauncher/instances/Test/.minecraft/config/ChatTriggers/modules/PolarClient/socket/Socket.js:78)
	at org.mozilla.javascript.gen.file__C__Users_DELL_AppData_Roaming_PrismLauncher_instances_Test__minecraft_config_ChatTriggers_modules_PolarClient_socket_Socket_js_373.call(file:/C:/Users/DELL/AppData/Roaming/PrismLauncher/instances/Test/.minecraft/config/ChatTriggers/modules/PolarClient/socket/Socket.js)
	at org.mozilla.javascript.gen.file__C__Users_DELL_AppData_Roaming_PrismLauncher_instances_Test__minecraft_config_ChatTriggers_modules_PolarClient_socket_Socket_js_373.exec(file:/C:/Users/DELL/AppData/Roaming/PrismLauncher/instances/Test/.minecraft/config/ChatTriggers/modules/PolarClient/socket/Socket.js)
	at org.mozilla.javascript.commonjs.module.Require.executeModuleScript(Require.java:351)
	at org.mozilla.javascript.commonjs.module.Require.getExportedModuleInterface(Require.java:302)
	at org.mozilla.javascript.commonjs.module.Require.call(Require.java:232)
	at org.mozilla.javascript.optimizer.OptRuntime.callName(OptRuntime.java:74)
	at org.mozilla.javascript.gen.file__C__Users_DELL_AppData_Roaming_PrismLauncher_instances_Test__minecraft___config_ChatTriggers_modules_PolarClient_loader_js_317._c_script_0(file:/C:/Users/DELL/AppData/Roaming/PrismLauncher/instances/Test/.minecraft/./config/ChatTriggers/modules/PolarClient/loader.js:1)
	at org.mozilla.javascript.gen.file__C__Users_DELL_AppData_Roaming_PrismLauncher_instances_Test__minecraft___config_ChatTriggers_modules_PolarClient_loader_js_317.call(file:/C:/Users/DELL/AppData/Roaming/PrismLauncher/instances/Test/.minecraft/./config/ChatTriggers/modules/PolarClient/loader.js)
	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:342)
	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3951)
	at org.mozilla.javascript.gen.file__C__Users_DELL_AppData_Roaming_PrismLauncher_instances_Test__minecraft___config_ChatTriggers_modules_PolarClient_loader_js_317.call(file:/C:/Users/DELL/AppData/Roaming/PrismLauncher/instances/Test/.minecraft/./config/ChatTriggers/modules/PolarClient/loader.js)
	at org.mozilla.javascript.gen.file__C__Users_DELL_AppData_Roaming_PrismLauncher_instances_Test__minecraft___config_ChatTriggers_modules_PolarClient_loader_js_317.exec(file:/C:/Users/DELL/AppData/Roaming/PrismLauncher/instances/Test/.minecraft/./config/ChatTriggers/modules/PolarClient/loader.js)
	at org.mozilla.javascript.commonjs.module.Require.executeModuleScript(Require.java:351)
	at org.mozilla.javascript.commonjs.module.Require.getExportedModuleInterface(Require.java:302)
	at com.chattriggers.ctjs.engine.langs.js.JSLoader$CTRequire.loadCTModule(JSLoader.kt:329)
	at com.chattriggers.ctjs.engine.langs.js.JSLoader.entryPass(JSLoader.kt:154)
	at com.chattriggers.ctjs.engine.module.ModuleManager.entryPass(ModuleManager.kt:127)
	at com.chattriggers.ctjs.engine.module.ModuleManager.entryPass$default(ModuleManager.kt:116)
	at com.chattriggers.ctjs.Reference$loadCT$1.invoke(Reference.kt:71)
	at com.chattriggers.ctjs.Reference$loadCT$1.invoke(Reference.kt:69)
	at com.chattriggers.ctjs.Reference$conditionalThread$1.invoke(Reference.kt:108)
	at com.chattriggers.ctjs.Reference$conditionalThread$1.invoke(Reference.kt:106)
	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)

`
